//查询面板
export const SET_MODEL_VAL = 'SET_MODEL_VAL'
export const SET_TABLE_DATA = 'SET_TABLE_DATA'
export const SET_TOTAL_DATA = 'SET_TOTAL_DATA'
export const SET_EDIT_VODAL = 'SET_EDIT_VODAL'
export const RESET_EDIT_MODEL = 'RESET_EDIT_MODEL'